baseURL = "http://127.0.0.1:1313"
languageCode = "en-gb"
title = "Jamore Fanpage"
theme = "vintage-web-hugo-theme"

# Pagination
[pagination]
  pagerSize = 10
  path = "page"

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 30

# Theme Parameters
[params]
  # Site Description
  description = "A Fanpage for Top Sigma Jamore"
  author = "A Jamore Fan"

  custom_css = "css/override.css"

  # Retro Features
  show_browser_chrome = false
  show_status_bar = false
  show_sidebar = true
  show_welcome_message = true
  welcome_message = "chat, am i cooked? – fake drillers, go home – get mogged – if you are reading this, you are gay – never goon, only edge – why are you gae"

  # Content Display
  show_featured_sections = false
  show_stats = true
  show_retro_elements = true
  show_sharing = true

  # Footer Options
  show_retro_footer = true
  show_build_info = false

  # Sidebar Options
  show_sidebar_stats = true
  show_retro_sidebar = true
  sidebar_content = "Welcome to the Peak Male Experience – Jamore’s Fanpage Is Where It’s At."

  # Social Links
  [params.social]
    instagram = "human_hamez"

  # Repository (for edit links)
  repo_url = "https://github.com/username/repo"
  edit_page = false
